import { createContext, useContext, useState, useCallback } from 'react';

const translations = {
  en: {
    // General
    appName: 'MekongPOS',
    welcome: 'Welcome',
    search: 'Search',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    confirm: 'Confirm',
    close: 'Close',
    actions: 'Actions',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    yes: 'Yes',
    no: 'No',
    loading: 'Loading...',
    noData: 'No data found',
    required: 'Required',
    optional: 'Optional',
    all: 'All',
    filter: 'Filter',
    export: 'Export',
    download: 'Download',
    refresh: 'Refresh',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    showing: 'Showing',
    of: 'of',
    results: 'results',
    success: 'Success',
    error: 'Error',
    warning: 'Warning',

    // Navigation
    dashboard: 'Dashboard',
    products: 'Products',
    categories: 'Categories',
    pointOfSale: 'Point of Sale',
    pos: 'POS',
    sales: 'Sales',
    salesHistory: 'Sales History',
    stock: 'Stock',
    stockManagement: 'Stock Management',
    reports: 'Reports',
    salesReport: 'Sales Report',
    users: 'Users',
    customers: 'Customers',
    settings: 'Settings',
    menu: 'Menu',
    mainMenu: 'Main Menu',
    management: 'Management',

    // Auth
    login: 'Login',
    logout: 'Logout',
    username: 'Username',
    password: 'Password',
    loginTitle: 'Sign in to your account',
    loginSubtitle: 'Enter your credentials to access the system',
    loginButton: 'Sign In',
    loginError: 'Invalid username or password',
    loggingIn: 'Signing in...',
    sessionExpired: 'Session expired. Please login again.',

    // Products
    productName: 'Product Name',
    barcode: 'Barcode',
    category: 'Category',
    costPrice: 'Cost Price',
    sellPrice: 'Sell Price',
    price: 'Price',
    quantity: 'Quantity',
    qty: 'Qty',
    unit: 'Unit',
    description: 'Description',
    image: 'Image',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    deleteProduct: 'Delete Product',
    productCreated: 'Product created successfully',
    productUpdated: 'Product updated successfully',
    productDeleted: 'Product deleted successfully',
    noProducts: 'No products found',
    searchProducts: 'Search products...',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    stockQty: 'Stock Qty',
    minStock: 'Min Stock',
    generateBarcode: 'Generate',
    allCategories: 'All Categories',
    productImage: 'Product Image',
    uploadImage: 'Upload Image',
    removeImage: 'Remove Image',
    noImage: 'No Image',
    imageTooLarge: 'Image must be under 5MB',
    imageInvalidType: 'Only JPEG, PNG, GIF, or WEBP images allowed',

    // Categories
    categoryName: 'Category Name',
    addCategory: 'Add Category',
    editCategory: 'Edit Category',
    deleteCategory: 'Delete Category',
    categoryCreated: 'Category created successfully',
    categoryUpdated: 'Category updated successfully',
    categoryDeleted: 'Category deleted successfully',
    productsCount: 'Products',
    noCategories: 'No categories found',

    // POS
    currentSale: 'Current Sale',
    clearCart: 'Clear Cart',
    addToCart: 'Add to Cart',
    emptyCart: 'Cart is empty',
    emptyCartMsg: 'Add products to start a sale',
    checkout: 'Checkout',
    payNow: 'Pay Now',
    scanBarcode: 'Scan barcode or search...',
    newSale: 'New Sale',
    items: 'items',
    item: 'item',

    // Payment
    payment: 'Payment',
    paymentMethod: 'Payment Method',
    cash: 'Cash',
    card: 'Card',
    amountPaid: 'Amount Paid',
    amountDue: 'Amount Due',
    change: 'Change',
    exact: 'Exact',
    confirmPayment: 'Confirm Payment',
    saleCompleted: 'Sale completed successfully!',
    insufficientAmount: 'Insufficient amount',
    processing: 'Processing...',

    // Totals
    subtotal: 'Subtotal',
    discount: 'Discount',
    discountType: 'Discount Type',
    percentage: 'Percentage',
    fixedAmount: 'Fixed Amount',
    tax: 'Tax',
    total: 'Total',
    grandTotal: 'Grand Total',

    // Receipt
    receipt: 'Receipt',
    printReceipt: 'Print Receipt',
    receiptNo: 'Receipt No',
    date: 'Date',
    time: 'Time',
    cashier: 'Cashier',
    thankYou: 'Thank you for your purchase!',
    invoice: 'Invoice',

    // Stock
    stockIn: 'Stock In',
    stockOut: 'Stock Out',
    adjustment: 'Adjustment',
    reference: 'Reference',
    note: 'Note',
    notes: 'Notes',
    movementHistory: 'Movement History',
    type: 'Type',
    selectProduct: 'Select Product',
    stockUpdated: 'Stock updated successfully',
    movements: 'Movements',
    currentStock: 'Current Stock',

    // Reports
    dailyReport: 'Daily Report',
    monthlyReport: 'Monthly Report',
    topProducts: 'Top Products',
    totalSales: 'Total Sales',
    totalRevenue: 'Total Revenue',
    averageSale: 'Average Sale',
    salesCount: 'Sales Count',
    revenue: 'Revenue',
    profit: 'Profit',
    period: 'Period',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    dateRange: 'Date Range',
    startDate: 'Start Date',
    endDate: 'End Date',
    groupBy: 'Group By',
    day: 'Day',
    month: 'Month',
    year: 'Year',
    exportCSV: 'Export CSV',

    // Users
    fullName: 'Full Name',
    role: 'Role',
    admin: 'Admin',
    addUser: 'Add User',
    editUser: 'Edit User',
    deleteUser: 'Delete User',
    userCreated: 'User created successfully',
    userUpdated: 'User updated successfully',
    userDeleted: 'User deleted successfully',
    resetPassword: 'Reset Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    toggleActive: 'Toggle Active',

    // Customers
    customerName: 'Customer Name',
    phone: 'Phone',
    email: 'Email',
    address: 'Address',
    points: 'Points',
    addCustomer: 'Add Customer',
    editCustomer: 'Edit Customer',
    deleteCustomer: 'Delete Customer',
    customerCreated: 'Customer created successfully',
    customerUpdated: 'Customer updated successfully',
    customerDeleted: 'Customer deleted successfully',
    searchCustomers: 'Search customers...',
    noCustomers: 'No customers found',
    purchaseHistory: 'Purchase History',

    // Settings
    shopInfo: 'Shop Information',
    shopName: 'Shop Name',
    shopAddress: 'Shop Address',
    shopPhone: 'Shop Phone',
    taxAndCurrency: 'Tax & Currency',
    taxRate: 'Tax Rate',
    exchangeRate: 'Exchange Rate',
    primaryCurrency: 'Primary Currency',
    secondaryCurrency: 'Secondary Currency',
    receiptSettings: 'Receipt Settings',
    receiptFooter: 'Receipt Footer Message',
    settingsSaved: 'Settings saved successfully',
    shopLogo: 'Shop Logo',
    uploadLogo: 'Upload Logo',
    currency: 'Currency',
    language: 'Language',
    english: 'English',
    khmer: 'ខ្មែរ',

    // Dashboard
    todaySales: "Today's Sales",
    todayRevenue: "Today's Revenue",
    totalProducts: 'Total Products',
    lowStockAlerts: 'Low Stock Alerts',
    recentSales: 'Recent Sales',
    topSellingProducts: 'Top Selling Products',
    salesOverview: 'Sales Overview',
    monthlySales: 'Monthly Sales',
    sold: 'sold',

    // Confirmation
    deleteConfirmTitle: 'Delete Confirmation',
    deleteConfirmText: 'Are you sure you want to delete this item? This action cannot be undone.',
    clearCartConfirm: 'Are you sure you want to clear the cart?',
  },

  km: {
    // General
    appName: 'MekongPOS',
    welcome: 'សូមស្វាគមន៍',
    search: 'ស្វែងរក',
    add: 'បន្ថែម',
    edit: 'កែប្រែ',
    delete: 'លុប',
    save: 'រក្សាទុក',
    cancel: 'បោះបង់',
    confirm: 'បញ្ជាក់',
    close: 'បិទ',
    actions: 'សកម្មភាព',
    status: 'ស្ថានភាព',
    active: 'សកម្ម',
    inactive: 'អសកម្ម',
    yes: 'បាទ/ចាស',
    no: 'ទេ',
    loading: 'កំពុងផ្ទុក...',
    noData: 'រកមិនឃើញទិន្នន័យ',
    required: 'ត្រូវការ',
    optional: 'ជាជម្រើស',
    all: 'ទាំងអស់',
    filter: 'តម្រង',
    export: 'នាំចេញ',
    download: 'ទាញយក',
    refresh: 'ផ្ទុកឡើងវិញ',
    back: 'ថយក្រោយ',
    next: 'បន្ទាប់',
    previous: 'មុន',
    showing: 'បង្ហាញ',
    of: 'នៃ',
    results: 'លទ្ធផល',
    success: 'ជោគជ័យ',
    error: 'កំហុស',
    warning: 'ព្រមាន',

    // Navigation
    dashboard: 'ផ្ទាំងគ្រប់គ្រង',
    products: 'ផលិតផល',
    categories: 'ប្រភេទ',
    pointOfSale: 'ចំណុចលក់',
    pos: 'POS',
    sales: 'ការលក់',
    salesHistory: 'ប្រវត្តិការលក់',
    stock: 'ស្តុក',
    stockManagement: 'គ្រប់គ្រងស្តុក',
    reports: 'របាយការណ៍',
    salesReport: 'របាយការណ៍លក់',
    users: 'អ្នកប្រើប្រាស់',
    customers: 'អតិថិជន',
    settings: 'ការកំណត់',
    menu: 'មឺនុយ',
    mainMenu: 'មឺនុយមេ',
    management: 'គ្រប់គ្រង',

    // Auth
    login: 'ចូលប្រើ',
    logout: 'ចាកចេញ',
    username: 'ឈ្មោះអ្នកប្រើ',
    password: 'ពាក្យសម្ងាត់',
    loginTitle: 'ចូលប្រើគណនីរបស់អ្នក',
    loginSubtitle: 'បញ្ចូលព័ត៌មានសម្គាល់របស់អ្នក',
    loginButton: 'ចូលប្រើ',
    loginError: 'ឈ្មោះអ្នកប្រើ ឬពាក្យសម្ងាត់មិនត្រឹមត្រូវ',
    loggingIn: 'កំពុងចូល...',
    sessionExpired: 'សុពលភាពផុតកំណត់។ សូមចូលម្ដងទៀត។',

    // Products
    productName: 'ឈ្មោះផលិតផល',
    barcode: 'បាកូដ',
    category: 'ប្រភេទ',
    costPrice: 'តម្លៃដើម',
    sellPrice: 'តម្លៃលក់',
    price: 'តម្លៃ',
    quantity: 'បរិមាណ',
    qty: 'ចំនួន',
    unit: 'ឯកតា',
    description: 'ការពិពណ៌នា',
    image: 'រូបភាព',
    addProduct: 'បន្ថែមផលិតផល',
    editProduct: 'កែប្រែផលិតផល',
    deleteProduct: 'លុបផលិតផល',
    productCreated: 'បង្កើតផលិតផលដោយជោគជ័យ',
    productUpdated: 'ធ្វើបច្ចុប្បន្នភាពផលិតផលដោយជោគជ័យ',
    productDeleted: 'លុបផលិតផលដោយជោគជ័យ',
    noProducts: 'រកមិនឃើញផលិតផល',
    searchProducts: 'ស្វែងរកផលិតផល...',
    lowStock: 'ស្តុកទាប',
    outOfStock: 'អស់ពីស្តុក',
    inStock: 'មានក្នុងស្តុក',
    stockQty: 'ចំនួនស្តុក',
    minStock: 'ស្តុកអប្បបរមា',
    generateBarcode: 'បង្កើត',
    allCategories: 'ប្រភេទទាំងអស់',
    productImage: 'រូបភាពផលិតផល',
    uploadImage: 'បង្ហោះរូបភាព',
    removeImage: 'លុបរូបភាព',
    noImage: 'មិនមានរូបភាព',
    imageTooLarge: 'រូបភាពត្រូវតែតិចជាង 5MB',
    imageInvalidType: 'អនុញ្ញាតតែ JPEG, PNG, GIF, ឬ WEBP ប៉ុណ្ណោះ',

    // Categories
    categoryName: 'ឈ្មោះប្រភេទ',
    addCategory: 'បន្ថែមប្រភេទ',
    editCategory: 'កែប្រែប្រភេទ',
    deleteCategory: 'លុបប្រភេទ',
    categoryCreated: 'បង្កើតប្រភេទដោយជោគជ័យ',
    categoryUpdated: 'ធ្វើបច្ចុប្បន្នភាពប្រភេទដោយជោគជ័យ',
    categoryDeleted: 'លុបប្រភេទដោយជោគជ័យ',
    productsCount: 'ផលិតផល',
    noCategories: 'រកមិនឃើញប្រភេទ',

    // POS
    currentSale: 'ការលក់បច្ចុប្បន្ន',
    clearCart: 'សម្អាតកន្ត្រក',
    addToCart: 'ដាក់ក្នុងកន្ត្រក',
    emptyCart: 'កន្ត្រកទទេ',
    emptyCartMsg: 'បន្ថែមផលិតផលដើម្បីចាប់ផ្ដើមលក់',
    checkout: 'ទូទាត់',
    payNow: 'បង់ឥឡូវ',
    scanBarcode: 'ស្កេនបាកូដ ឬស្វែងរក...',
    newSale: 'ការលក់ថ្មី',
    items: 'មុខ',
    item: 'មុខ',

    // Payment
    payment: 'ការទូទាត់',
    paymentMethod: 'វិធីបង់ប្រាក់',
    cash: 'សាច់ប្រាក់',
    card: 'កាត',
    amountPaid: 'ចំនួនបង់',
    amountDue: 'ចំនួនត្រូវបង់',
    change: 'ប្រាក់អាប់',
    exact: 'ចំនួនពិតប្រាកដ',
    confirmPayment: 'បញ្ជាក់ការទូទាត់',
    saleCompleted: 'ការលក់បានបញ្ចប់ដោយជោគជ័យ!',
    insufficientAmount: 'ចំនួនមិនគ្រប់គ្រាន់',
    processing: 'កំពុងដំណើរការ...',

    // Totals
    subtotal: 'សរុបរង',
    discount: 'បញ្ចុះតម្លៃ',
    discountType: 'ប្រភេទបញ្ចុះតម្លៃ',
    percentage: 'ភាគរយ',
    fixedAmount: 'ចំនួនថេរ',
    tax: 'ពន្ធ',
    total: 'សរុប',
    grandTotal: 'សរុបរួម',

    // Receipt
    receipt: 'បង្កាន់ដៃ',
    printReceipt: 'បោះពុម្ពបង្កាន់ដៃ',
    receiptNo: 'លេខបង្កាន់ដៃ',
    date: 'កាលបរិច្ឆេទ',
    time: 'ម៉ោង',
    cashier: 'អ្នកគិតប្រាក់',
    thankYou: 'សូមអរគុណសម្រាប់ការទិញ!',
    invoice: 'វិក្កយបត្រ',

    // Stock
    stockIn: 'ស្តុកចូល',
    stockOut: 'ស្តុកចេញ',
    adjustment: 'កែតម្រូវ',
    reference: 'យោង',
    note: 'កំណត់ចំណាំ',
    notes: 'កំណត់ចំណាំ',
    movementHistory: 'ប្រវត្តិចលនា',
    type: 'ប្រភេទ',
    selectProduct: 'ជ្រើសរើសផលិតផល',
    stockUpdated: 'ធ្វើបច្ចុប្បន្នភាពស្តុកដោយជោគជ័យ',
    movements: 'ចលនា',
    currentStock: 'ស្តុកបច្ចុប្បន្ន',

    // Reports
    dailyReport: 'របាយការណ៍ប្រចាំថ្ងៃ',
    monthlyReport: 'របាយការណ៍ប្រចាំខែ',
    topProducts: 'ផលិតផលលក់ដាច់បំផុត',
    totalSales: 'ការលក់សរុប',
    totalRevenue: 'ចំណូលសរុប',
    averageSale: 'ការលក់មធ្យម',
    salesCount: 'ចំនួនការលក់',
    revenue: 'ចំណូល',
    profit: 'ប្រាក់ចំណេញ',
    period: 'រយៈពេល',
    today: 'ថ្ងៃនេះ',
    thisWeek: 'សប្ដាហ៍នេះ',
    thisMonth: 'ខែនេះ',
    dateRange: 'ចន្លោះកាលបរិច្ឆេទ',
    startDate: 'ថ្ងៃចាប់ផ្ដើម',
    endDate: 'ថ្ងៃបញ្ចប់',
    groupBy: 'ដាក់ជាក្រុមតាម',
    day: 'ថ្ងៃ',
    month: 'ខែ',
    year: 'ឆ្នាំ',
    exportCSV: 'នាំចេញ CSV',

    // Users
    fullName: 'ឈ្មោះពេញ',
    role: 'តួនាទី',
    admin: 'អ្នកគ្រប់គ្រង',
    addUser: 'បន្ថែមអ្នកប្រើ',
    editUser: 'កែប្រែអ្នកប្រើ',
    deleteUser: 'លុបអ្នកប្រើ',
    userCreated: 'បង្កើតអ្នកប្រើដោយជោគជ័យ',
    userUpdated: 'ធ្វើបច្ចុប្បន្នភាពអ្នកប្រើដោយជោគជ័យ',
    userDeleted: 'លុបអ្នកប្រើដោយជោគជ័យ',
    resetPassword: 'កំណត់ពាក្យសម្ងាត់ឡើងវិញ',
    newPassword: 'ពាក្យសម្ងាត់ថ្មី',
    confirmPassword: 'បញ្ជាក់ពាក្យសម្ងាត់',
    toggleActive: 'បិទ/បើក',

    // Customers
    customerName: 'ឈ្មោះអតិថិជន',
    phone: 'ទូរស័ព្ទ',
    email: 'អ៊ីមែល',
    address: 'អាសយដ្ឋាន',
    points: 'ពិន្ទុ',
    addCustomer: 'បន្ថែមអតិថិជន',
    editCustomer: 'កែប្រែអតិថិជន',
    deleteCustomer: 'លុបអតិថិជន',
    customerCreated: 'បង្កើតអតិថិជនដោយជោគជ័យ',
    customerUpdated: 'ធ្វើបច្ចុប្បន្នភាពអតិថិជនដោយជោគជ័យ',
    customerDeleted: 'លុបអតិថិជនដោយជោគជ័យ',
    searchCustomers: 'ស្វែងរកអតិថិជន...',
    noCustomers: 'រកមិនឃើញអតិថិជន',
    purchaseHistory: 'ប្រវត្តិការទិញ',

    // Settings
    shopInfo: 'ព័ត៌មានហាង',
    shopName: 'ឈ្មោះហាង',
    shopAddress: 'អាសយដ្ឋានហាង',
    shopPhone: 'ទូរស័ព្ទហាង',
    taxAndCurrency: 'ពន្ធ និងរូបិយប័ណ្ណ',
    taxRate: 'អត្រាពន្ធ',
    exchangeRate: 'អត្រាប្ដូរ',
    primaryCurrency: 'រូបិយប័ណ្ណចម្បង',
    secondaryCurrency: 'រូបិយប័ណ្ណបន្ទាប់បន្សំ',
    receiptSettings: 'ការកំណត់បង្កាន់ដៃ',
    receiptFooter: 'សារនៅខាងក្រោមបង្កាន់ដៃ',
    settingsSaved: 'រក្សាទុកការកំណត់ដោយជោគជ័យ',
    shopLogo: 'ឡូហ្គោហាង',
    uploadLogo: 'បង្ហោះឡូហ្គោ',
    currency: 'រូបិយប័ណ្ណ',
    language: 'ភាសា',
    english: 'English',
    khmer: 'ខ្មែរ',

    // Dashboard
    todaySales: 'ការលក់ថ្ងៃនេះ',
    todayRevenue: 'ចំណូលថ្ងៃនេះ',
    totalProducts: 'ផលិតផលសរុប',
    lowStockAlerts: 'ការជូនដំណឹងស្តុកទាប',
    recentSales: 'ការលក់ថ្មីៗ',
    topSellingProducts: 'ផលិតផលលក់ដាច់បំផុត',
    salesOverview: 'ទិដ្ឋភាពទូទៅនៃការលក់',
    monthlySales: 'ការលក់ប្រចាំខែ',
    sold: 'លក់បាន',

    // Confirmation
    deleteConfirmTitle: 'បញ្ជាក់ការលុប',
    deleteConfirmText: 'តើអ្នកប្រាកដទេថាចង់លុបធាតុនេះ? សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។',
    clearCartConfirm: 'តើអ្នកប្រាកដទេថាចង់សម្អាតកន្ត្រក?',
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(
    () => localStorage.getItem('mekongpos_lang') || 'en'
  );

  const setLanguage = useCallback((lang) => {
    setLanguageState(lang);
    localStorage.setItem('mekongpos_lang', lang);
  }, []);

  const toggleLanguage = useCallback(() => {
    setLanguage(language === 'en' ? 'km' : 'en');
  }, [language, setLanguage]);

  const t = useCallback(
    (key) => {
      return translations[language]?.[key] || translations.en?.[key] || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, t, toggleLanguage, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}

export default LanguageContext;
